title: Hello awesome human, I'm happy fot having you here
author: Fiorella Salgado R.
email: youareincredible@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Be happy. You are an awesome person. Don't worry about the thing that yoy could not change, just take a breath and 
keep going
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
